// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/storage/v1/arrow.proto

package com.google.cloud.bigquery.storage.v1;

public interface ArrowSerializationOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1.ArrowSerializationOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The compression codec to use for Arrow buffers in serialized record
   * batches.
   * </pre>
   *
   * <code>.google.cloud.bigquery.storage.v1.ArrowSerializationOptions.CompressionCodec buffer_compression = 2;</code>
   * @return The enum numeric value on the wire for bufferCompression.
   */
  int getBufferCompressionValue();
  /**
   * <pre>
   * The compression codec to use for Arrow buffers in serialized record
   * batches.
   * </pre>
   *
   * <code>.google.cloud.bigquery.storage.v1.ArrowSerializationOptions.CompressionCodec buffer_compression = 2;</code>
   * @return The bufferCompression.
   */
  com.google.cloud.bigquery.storage.v1.ArrowSerializationOptions.CompressionCodec getBufferCompression();
}
