// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/storage/v1/avro.proto

package com.google.cloud.bigquery.storage.v1;

public interface AvroRowsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1.AvroRows)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Binary serialized rows in a block.
   * </pre>
   *
   * <code>bytes serialized_binary_rows = 1;</code>
   * @return The serializedBinaryRows.
   */
  com.google.protobuf.ByteString getSerializedBinaryRows();

  /**
   * <pre>
   * [Deprecated] The count of rows in the returning block.
   * Please use the format-independent ReadRowsResponse.row_count instead.
   * </pre>
   *
   * <code>int64 row_count = 2 [deprecated = true];</code>
   * @deprecated google.cloud.bigquery.storage.v1.AvroRows.row_count is deprecated.
   *     See google/cloud/bigquery/storage/v1/avro.proto;l=39
   * @return The rowCount.
   */
  @java.lang.Deprecated long getRowCount();
}
