// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/storage/v1/avro.proto

package com.google.cloud.bigquery.storage.v1;

public interface AvroRowsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1.AvroRows)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Binary serialized rows in a block.
   * </pre>
   *
   * <code>bytes serialized_binary_rows = 1;</code>
   * @return The serializedBinaryRows.
   */
  com.google.protobuf.ByteString getSerializedBinaryRows();

  /**
   * <pre>
   * The count of rows in the returning block.
   * </pre>
   *
   * <code>int64 row_count = 2;</code>
   * @return The rowCount.
   */
  long getRowCount();
}
