// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/storage/v1/avro.proto

package com.google.cloud.bigquery.storage.v1;

public interface AvroSchemaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1.AvroSchema)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Json serialized schema, as described at
   * https://avro.apache.org/docs/1.8.1/spec.html.
   * </pre>
   *
   * <code>string schema = 1;</code>
   * @return The schema.
   */
  java.lang.String getSchema();
  /**
   * <pre>
   * Json serialized schema, as described at
   * https://avro.apache.org/docs/1.8.1/spec.html.
   * </pre>
   *
   * <code>string schema = 1;</code>
   * @return The bytes for schema.
   */
  com.google.protobuf.ByteString
      getSchemaBytes();
}
