// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/storage/v1/storage.proto

package com.google.cloud.bigquery.storage.v1;

public interface FinalizeWriteStreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1.FinalizeWriteStreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Number of rows in the finalized stream.
   * </pre>
   *
   * <code>int64 row_count = 1;</code>
   * @return The rowCount.
   */
  long getRowCount();
}
