// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/storage/v1/storage.proto

// Protobuf Java Version: 3.25.3
package com.google.cloud.bigquery.storage.v1;

public interface RowErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1.RowError)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Index of the malformed row in the request.
   * </pre>
   *
   * <code>int64 index = 1;</code>
   * @return The index.
   */
  long getIndex();

  /**
   * <pre>
   * Structured error reason for a row error.
   * </pre>
   *
   * <code>.google.cloud.bigquery.storage.v1.RowError.RowErrorCode code = 2;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <pre>
   * Structured error reason for a row error.
   * </pre>
   *
   * <code>.google.cloud.bigquery.storage.v1.RowError.RowErrorCode code = 2;</code>
   * @return The code.
   */
  com.google.cloud.bigquery.storage.v1.RowError.RowErrorCode getCode();

  /**
   * <pre>
   * Description of the issue encountered when processing the row.
   * </pre>
   *
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Description of the issue encountered when processing the row.
   * </pre>
   *
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
