// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/storage/v1/table.proto

package com.google.cloud.bigquery.storage.v1;

public interface TableSchemaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1.TableSchema)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Describes the fields in a table.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.storage.v1.TableFieldSchema fields = 1;</code>
   */
  java.util.List<com.google.cloud.bigquery.storage.v1.TableFieldSchema> 
      getFieldsList();
  /**
   * <pre>
   * Describes the fields in a table.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.storage.v1.TableFieldSchema fields = 1;</code>
   */
  com.google.cloud.bigquery.storage.v1.TableFieldSchema getFields(int index);
  /**
   * <pre>
   * Describes the fields in a table.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.storage.v1.TableFieldSchema fields = 1;</code>
   */
  int getFieldsCount();
  /**
   * <pre>
   * Describes the fields in a table.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.storage.v1.TableFieldSchema fields = 1;</code>
   */
  java.util.List<? extends com.google.cloud.bigquery.storage.v1.TableFieldSchemaOrBuilder> 
      getFieldsOrBuilderList();
  /**
   * <pre>
   * Describes the fields in a table.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.storage.v1.TableFieldSchema fields = 1;</code>
   */
  com.google.cloud.bigquery.storage.v1.TableFieldSchemaOrBuilder getFieldsOrBuilder(
      int index);
}
