// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/storage/v1beta2/arrow.proto

package com.google.cloud.bigquery.storage.v1beta2;

public interface ArrowSchemaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1beta2.ArrowSchema)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * IPC serialized Arrow schema.
   * </pre>
   *
   * <code>bytes serialized_schema = 1;</code>
   * @return The serializedSchema.
   */
  com.google.protobuf.ByteString getSerializedSchema();
}
