// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/storage/v1beta2/arrow.proto

package com.google.cloud.bigquery.storage.v1beta2;

public interface ArrowSerializationOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1beta2.ArrowSerializationOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The Arrow IPC format to use.
   * </pre>
   *
   * <code>.google.cloud.bigquery.storage.v1beta2.ArrowSerializationOptions.Format format = 1;</code>
   * @return The enum numeric value on the wire for format.
   */
  int getFormatValue();
  /**
   * <pre>
   * The Arrow IPC format to use.
   * </pre>
   *
   * <code>.google.cloud.bigquery.storage.v1beta2.ArrowSerializationOptions.Format format = 1;</code>
   * @return The format.
   */
  com.google.cloud.bigquery.storage.v1beta2.ArrowSerializationOptions.Format getFormat();
}
