// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/storage/v1beta2/protobuf.proto

package com.google.cloud.bigquery.storage.v1beta2;

public interface ProtoSchemaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1beta2.ProtoSchema)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Descriptor for input message. The descriptor has to be self contained,
   * including all the nested types, excepted for proto buffer well known types
   * (https://developers.google.com/protocol-buffers/docs/reference/google.protobuf).
   * </pre>
   *
   * <code>.google.protobuf.DescriptorProto proto_descriptor = 1;</code>
   * @return Whether the protoDescriptor field is set.
   */
  boolean hasProtoDescriptor();
  /**
   * <pre>
   * Descriptor for input message. The descriptor has to be self contained,
   * including all the nested types, excepted for proto buffer well known types
   * (https://developers.google.com/protocol-buffers/docs/reference/google.protobuf).
   * </pre>
   *
   * <code>.google.protobuf.DescriptorProto proto_descriptor = 1;</code>
   * @return The protoDescriptor.
   */
  com.google.protobuf.DescriptorProtos.DescriptorProto getProtoDescriptor();
  /**
   * <pre>
   * Descriptor for input message. The descriptor has to be self contained,
   * including all the nested types, excepted for proto buffer well known types
   * (https://developers.google.com/protocol-buffers/docs/reference/google.protobuf).
   * </pre>
   *
   * <code>.google.protobuf.DescriptorProto proto_descriptor = 1;</code>
   */
  com.google.protobuf.DescriptorProtos.DescriptorProtoOrBuilder getProtoDescriptorOrBuilder();
}
