// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/bigquery/storage/v1beta2/protobuf.proto

package com.google.cloud.bigquery.storage.v1beta2;

public interface ProtoRowsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1beta2.ProtoRows)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A sequence of rows serialized as a Protocol Buffer.
   * See https://developers.google.com/protocol-buffers/docs/overview for more
   * information on deserializing this field.
   * </pre>
   *
   * <code>repeated bytes serialized_rows = 1;</code>
   * @return A list containing the serializedRows.
   */
  java.util.List<com.google.protobuf.ByteString> getSerializedRowsList();
  /**
   * <pre>
   * A sequence of rows serialized as a Protocol Buffer.
   * See https://developers.google.com/protocol-buffers/docs/overview for more
   * information on deserializing this field.
   * </pre>
   *
   * <code>repeated bytes serialized_rows = 1;</code>
   * @return The count of serializedRows.
   */
  int getSerializedRowsCount();
  /**
   * <pre>
   * A sequence of rows serialized as a Protocol Buffer.
   * See https://developers.google.com/protocol-buffers/docs/overview for more
   * information on deserializing this field.
   * </pre>
   *
   * <code>repeated bytes serialized_rows = 1;</code>
   * @param index The index of the element to return.
   * @return The serializedRows at the given index.
   */
  com.google.protobuf.ByteString getSerializedRows(int index);
}
