// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1beta2/arrow.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1beta2;

@com.google.protobuf.Generated
public interface ArrowSchemaOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1beta2.ArrowSchema)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * IPC serialized Arrow schema.
   * </pre>
   *
   * <code>bytes serialized_schema = 1;</code>
   *
   * @return The serializedSchema.
   */
  com.google.protobuf.ByteString getSerializedSchema();
}
