// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1beta2/avro.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1beta2;

@com.google.protobuf.Generated
public interface AvroRowsOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1beta2.AvroRows)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Binary serialized rows in a block.
   * </pre>
   *
   * <code>bytes serialized_binary_rows = 1;</code>
   *
   * @return The serializedBinaryRows.
   */
  com.google.protobuf.ByteString getSerializedBinaryRows();
}
