// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1/arrow.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1;

@com.google.protobuf.Generated
public interface ArrowSerializationOptionsOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1.ArrowSerializationOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The compression codec to use for Arrow buffers in serialized record
   * batches.
   * </pre>
   *
   * <code>
   * .google.cloud.bigquery.storage.v1.ArrowSerializationOptions.CompressionCodec buffer_compression = 2;
   * </code>
   *
   * @return The enum numeric value on the wire for bufferCompression.
   */
  int getBufferCompressionValue();

  /**
   *
   *
   * <pre>
   * The compression codec to use for Arrow buffers in serialized record
   * batches.
   * </pre>
   *
   * <code>
   * .google.cloud.bigquery.storage.v1.ArrowSerializationOptions.CompressionCodec buffer_compression = 2;
   * </code>
   *
   * @return The bufferCompression.
   */
  com.google.cloud.bigquery.storage.v1.ArrowSerializationOptions.CompressionCodec
      getBufferCompression();

  /**
   *
   *
   * <pre>
   * Optional. Set timestamp precision option. If not set, the default precision
   * is microseconds.
   * </pre>
   *
   * <code>
   * .google.cloud.bigquery.storage.v1.ArrowSerializationOptions.PicosTimestampPrecision picos_timestamp_precision = 3;
   * </code>
   *
   * @return The enum numeric value on the wire for picosTimestampPrecision.
   */
  int getPicosTimestampPrecisionValue();

  /**
   *
   *
   * <pre>
   * Optional. Set timestamp precision option. If not set, the default precision
   * is microseconds.
   * </pre>
   *
   * <code>
   * .google.cloud.bigquery.storage.v1.ArrowSerializationOptions.PicosTimestampPrecision picos_timestamp_precision = 3;
   * </code>
   *
   * @return The picosTimestampPrecision.
   */
  com.google.cloud.bigquery.storage.v1.ArrowSerializationOptions.PicosTimestampPrecision
      getPicosTimestampPrecision();
}
