// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1/arrow.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1;

@com.google.protobuf.Generated
public interface ArrowRecordBatchOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1.ArrowRecordBatch)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * IPC-serialized Arrow RecordBatch.
   * </pre>
   *
   * <code>bytes serialized_record_batch = 1;</code>
   *
   * @return The serializedRecordBatch.
   */
  com.google.protobuf.ByteString getSerializedRecordBatch();

  /**
   *
   *
   * <pre>
   * [Deprecated] The count of rows in `serialized_record_batch`.
   * Please use the format-independent ReadRowsResponse.row_count instead.
   * </pre>
   *
   * <code>int64 row_count = 2 [deprecated = true];</code>
   *
   * @deprecated google.cloud.bigquery.storage.v1.ArrowRecordBatch.row_count is deprecated. See
   *     google/cloud/bigquery/storage/v1/arrow.proto;l=43
   * @return The rowCount.
   */
  @java.lang.Deprecated
  long getRowCount();
}
