// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1/storage.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1;

@com.google.protobuf.Generated
public interface ThrottleStateOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1.ThrottleState)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * How much this connection is being throttled. Zero means no throttling,
   * 100 means fully throttled.
   * </pre>
   *
   * <code>int32 throttle_percent = 1;</code>
   *
   * @return The throttlePercent.
   */
  int getThrottlePercent();
}
