// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1beta/partition.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1beta;

@com.google.protobuf.Generated
public interface MetastorePartitionListOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1beta.MetastorePartitionList)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. List of partitions.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1beta.MetastorePartition partitions = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  java.util.List<com.google.cloud.bigquery.storage.v1beta.MetastorePartition> getPartitionsList();

  /**
   *
   *
   * <pre>
   * Required. List of partitions.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1beta.MetastorePartition partitions = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  com.google.cloud.bigquery.storage.v1beta.MetastorePartition getPartitions(int index);

  /**
   *
   *
   * <pre>
   * Required. List of partitions.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1beta.MetastorePartition partitions = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  int getPartitionsCount();

  /**
   *
   *
   * <pre>
   * Required. List of partitions.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1beta.MetastorePartition partitions = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  java.util.List<? extends com.google.cloud.bigquery.storage.v1beta.MetastorePartitionOrBuilder>
      getPartitionsOrBuilderList();

  /**
   *
   *
   * <pre>
   * Required. List of partitions.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1beta.MetastorePartition partitions = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  com.google.cloud.bigquery.storage.v1beta.MetastorePartitionOrBuilder getPartitionsOrBuilder(
      int index);
}
