// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1beta/metastore_partition.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1beta;

@com.google.protobuf.Generated
public interface StreamMetastorePartitionsResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1beta.StreamMetastorePartitionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Total count of partitions streamed by the client during the lifetime of the
   * stream. This is only set in the final response message before closing the
   * stream.
   * </pre>
   *
   * <code>int64 total_partitions_streamed_count = 2;</code>
   *
   * @return The totalPartitionsStreamedCount.
   */
  long getTotalPartitionsStreamedCount();

  /**
   *
   *
   * <pre>
   * Total count of partitions inserted by the server during the lifetime of the
   * stream. This is only set in the final response message before closing the
   * stream.
   * </pre>
   *
   * <code>int64 total_partitions_inserted_count = 3;</code>
   *
   * @return The totalPartitionsInsertedCount.
   */
  long getTotalPartitionsInsertedCount();
}
