// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1alpha/metastore_partition.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1alpha;

@com.google.protobuf.Generated
public interface BatchSizeTooLargeErrorOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1alpha.BatchSizeTooLargeError)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The maximum number of items that are supported in a single batch. This is
   * returned as a hint to the client to adjust the batch size.
   * </pre>
   *
   * <code>int64 max_batch_size = 1;</code>
   *
   * @return The maxBatchSize.
   */
  long getMaxBatchSize();

  /**
   *
   *
   * <pre>
   * Optional. The error message that is returned to the client.
   * </pre>
   *
   * <code>string error_message = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();

  /**
   *
   *
   * <pre>
   * Optional. The error message that is returned to the client.
   * </pre>
   *
   * <code>string error_message = 2 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString getErrorMessageBytes();
}
