// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1alpha/metastore_partition.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1alpha;

@com.google.protobuf.Generated
public interface BatchUpdateMetastorePartitionsResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1alpha.BatchUpdateMetastorePartitionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The list of metastore partitions that have been updated.
   * A maximum of 900 partitions can be updated in a batch.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.storage.v1alpha.MetastorePartition partitions = 1;</code>
   */
  java.util.List<com.google.cloud.bigquery.storage.v1alpha.MetastorePartition> getPartitionsList();

  /**
   *
   *
   * <pre>
   * The list of metastore partitions that have been updated.
   * A maximum of 900 partitions can be updated in a batch.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.storage.v1alpha.MetastorePartition partitions = 1;</code>
   */
  com.google.cloud.bigquery.storage.v1alpha.MetastorePartition getPartitions(int index);

  /**
   *
   *
   * <pre>
   * The list of metastore partitions that have been updated.
   * A maximum of 900 partitions can be updated in a batch.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.storage.v1alpha.MetastorePartition partitions = 1;</code>
   */
  int getPartitionsCount();

  /**
   *
   *
   * <pre>
   * The list of metastore partitions that have been updated.
   * A maximum of 900 partitions can be updated in a batch.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.storage.v1alpha.MetastorePartition partitions = 1;</code>
   */
  java.util.List<? extends com.google.cloud.bigquery.storage.v1alpha.MetastorePartitionOrBuilder>
      getPartitionsOrBuilderList();

  /**
   *
   *
   * <pre>
   * The list of metastore partitions that have been updated.
   * A maximum of 900 partitions can be updated in a batch.
   * </pre>
   *
   * <code>repeated .google.cloud.bigquery.storage.v1alpha.MetastorePartition partitions = 1;</code>
   */
  com.google.cloud.bigquery.storage.v1alpha.MetastorePartitionOrBuilder getPartitionsOrBuilder(
      int index);
}
