// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1alpha/metastore_partition.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1alpha;

@com.google.protobuf.Generated
public interface BatchUpdateMetastorePartitionsRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1alpha.BatchUpdateMetastorePartitionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. Reference to the table to which these metastore partitions
   * belong, in the format of
   * projects/{project}/locations/{location}/datasets/{dataset}/tables/{table}.
   * </pre>
   *
   * <code>
   * string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The parent.
   */
  java.lang.String getParent();

  /**
   *
   *
   * <pre>
   * Required. Reference to the table to which these metastore partitions
   * belong, in the format of
   * projects/{project}/locations/{location}/datasets/{dataset}/tables/{table}.
   * </pre>
   *
   * <code>
   * string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString getParentBytes();

  /**
   *
   *
   * <pre>
   * Required. Requests to update metastore partitions in the table.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1alpha.UpdateMetastorePartitionRequest requests = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  java.util.List<com.google.cloud.bigquery.storage.v1alpha.UpdateMetastorePartitionRequest>
      getRequestsList();

  /**
   *
   *
   * <pre>
   * Required. Requests to update metastore partitions in the table.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1alpha.UpdateMetastorePartitionRequest requests = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  com.google.cloud.bigquery.storage.v1alpha.UpdateMetastorePartitionRequest getRequests(int index);

  /**
   *
   *
   * <pre>
   * Required. Requests to update metastore partitions in the table.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1alpha.UpdateMetastorePartitionRequest requests = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  int getRequestsCount();

  /**
   *
   *
   * <pre>
   * Required. Requests to update metastore partitions in the table.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1alpha.UpdateMetastorePartitionRequest requests = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  java.util.List<
          ? extends
              com.google.cloud.bigquery.storage.v1alpha.UpdateMetastorePartitionRequestOrBuilder>
      getRequestsOrBuilderList();

  /**
   *
   *
   * <pre>
   * Required. Requests to update metastore partitions in the table.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1alpha.UpdateMetastorePartitionRequest requests = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  com.google.cloud.bigquery.storage.v1alpha.UpdateMetastorePartitionRequestOrBuilder
      getRequestsOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * Optional. Optional trace id to be used for debugging. It is expected that
   * the client sets the same `trace_id` for all the batches in the same
   * operation, so that it is possible to tie together the logs to all the
   * batches in the same operation. This is expected, but not required, to be
   * globally unique.
   * </pre>
   *
   * <code>string trace_id = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The traceId.
   */
  java.lang.String getTraceId();

  /**
   *
   *
   * <pre>
   * Optional. Optional trace id to be used for debugging. It is expected that
   * the client sets the same `trace_id` for all the batches in the same
   * operation, so that it is possible to tie together the logs to all the
   * batches in the same operation. This is expected, but not required, to be
   * globally unique.
   * </pre>
   *
   * <code>string trace_id = 4 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The bytes for traceId.
   */
  com.google.protobuf.ByteString getTraceIdBytes();
}
