// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1alpha/metastore_partition.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1alpha;

@com.google.protobuf.Generated
public interface CreateMetastorePartitionRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1alpha.CreateMetastorePartitionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. Reference to the table to where the metastore partition to be
   * added, in the format of
   * projects/{project}/databases/{databases}/tables/{table}.
   * </pre>
   *
   * <code>
   * string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The parent.
   */
  java.lang.String getParent();

  /**
   *
   *
   * <pre>
   * Required. Reference to the table to where the metastore partition to be
   * added, in the format of
   * projects/{project}/databases/{databases}/tables/{table}.
   * </pre>
   *
   * <code>
   * string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString getParentBytes();

  /**
   *
   *
   * <pre>
   * Required. The metastore partition to be added.
   * </pre>
   *
   * <code>
   * .google.cloud.bigquery.storage.v1alpha.MetastorePartition metastore_partition = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return Whether the metastorePartition field is set.
   */
  boolean hasMetastorePartition();

  /**
   *
   *
   * <pre>
   * Required. The metastore partition to be added.
   * </pre>
   *
   * <code>
   * .google.cloud.bigquery.storage.v1alpha.MetastorePartition metastore_partition = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return The metastorePartition.
   */
  com.google.cloud.bigquery.storage.v1alpha.MetastorePartition getMetastorePartition();

  /**
   *
   *
   * <pre>
   * Required. The metastore partition to be added.
   * </pre>
   *
   * <code>
   * .google.cloud.bigquery.storage.v1alpha.MetastorePartition metastore_partition = 2 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  com.google.cloud.bigquery.storage.v1alpha.MetastorePartitionOrBuilder
      getMetastorePartitionOrBuilder();
}
