// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1alpha/metastore_partition.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1alpha;

@com.google.protobuf.Generated
public interface ListMetastorePartitionsResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1alpha.ListMetastorePartitionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The list of partitions.
   * </pre>
   *
   * <code>.google.cloud.bigquery.storage.v1alpha.MetastorePartitionList partitions = 1;</code>
   *
   * @return Whether the partitions field is set.
   */
  boolean hasPartitions();

  /**
   *
   *
   * <pre>
   * The list of partitions.
   * </pre>
   *
   * <code>.google.cloud.bigquery.storage.v1alpha.MetastorePartitionList partitions = 1;</code>
   *
   * @return The partitions.
   */
  com.google.cloud.bigquery.storage.v1alpha.MetastorePartitionList getPartitions();

  /**
   *
   *
   * <pre>
   * The list of partitions.
   * </pre>
   *
   * <code>.google.cloud.bigquery.storage.v1alpha.MetastorePartitionList partitions = 1;</code>
   */
  com.google.cloud.bigquery.storage.v1alpha.MetastorePartitionListOrBuilder
      getPartitionsOrBuilder();

  /**
   *
   *
   * <pre>
   * The list of streams.
   * </pre>
   *
   * <code>.google.cloud.bigquery.storage.v1alpha.StreamList streams = 2;</code>
   *
   * @return Whether the streams field is set.
   */
  boolean hasStreams();

  /**
   *
   *
   * <pre>
   * The list of streams.
   * </pre>
   *
   * <code>.google.cloud.bigquery.storage.v1alpha.StreamList streams = 2;</code>
   *
   * @return The streams.
   */
  com.google.cloud.bigquery.storage.v1alpha.StreamList getStreams();

  /**
   *
   *
   * <pre>
   * The list of streams.
   * </pre>
   *
   * <code>.google.cloud.bigquery.storage.v1alpha.StreamList streams = 2;</code>
   */
  com.google.cloud.bigquery.storage.v1alpha.StreamListOrBuilder getStreamsOrBuilder();

  com.google.cloud.bigquery.storage.v1alpha.ListMetastorePartitionsResponse.ResponseCase
      getResponseCase();
}
