// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1alpha/partition.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1alpha;

@com.google.protobuf.Generated
public interface MetastorePartitionValuesOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1alpha.MetastorePartitionValues)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. The values of the partition keys, where each value corresponds to
   * a specific partition key in the order in which the keys are defined.
   * </pre>
   *
   * <code>repeated string values = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return A list containing the values.
   */
  java.util.List<java.lang.String> getValuesList();

  /**
   *
   *
   * <pre>
   * Required. The values of the partition keys, where each value corresponds to
   * a specific partition key in the order in which the keys are defined.
   * </pre>
   *
   * <code>repeated string values = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The count of values.
   */
  int getValuesCount();

  /**
   *
   *
   * <pre>
   * Required. The values of the partition keys, where each value corresponds to
   * a specific partition key in the order in which the keys are defined.
   * </pre>
   *
   * <code>repeated string values = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  java.lang.String getValues(int index);

  /**
   *
   *
   * <pre>
   * Required. The values of the partition keys, where each value corresponds to
   * a specific partition key in the order in which the keys are defined.
   * </pre>
   *
   * <code>repeated string values = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the values at the given index.
   */
  com.google.protobuf.ByteString getValuesBytes(int index);
}
