// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1alpha/partition.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1alpha;

@com.google.protobuf.Generated
public interface StreamListOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1alpha.StreamList)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Output only. List of streams.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1alpha.ReadStream streams = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  java.util.List<com.google.cloud.bigquery.storage.v1alpha.ReadStream> getStreamsList();

  /**
   *
   *
   * <pre>
   * Output only. List of streams.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1alpha.ReadStream streams = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  com.google.cloud.bigquery.storage.v1alpha.ReadStream getStreams(int index);

  /**
   *
   *
   * <pre>
   * Output only. List of streams.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1alpha.ReadStream streams = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  int getStreamsCount();

  /**
   *
   *
   * <pre>
   * Output only. List of streams.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1alpha.ReadStream streams = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  java.util.List<? extends com.google.cloud.bigquery.storage.v1alpha.ReadStreamOrBuilder>
      getStreamsOrBuilderList();

  /**
   *
   *
   * <pre>
   * Output only. List of streams.
   * </pre>
   *
   * <code>
   * repeated .google.cloud.bigquery.storage.v1alpha.ReadStream streams = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];
   * </code>
   */
  com.google.cloud.bigquery.storage.v1alpha.ReadStreamOrBuilder getStreamsOrBuilder(int index);
}
