// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/bigquery/storage/v1alpha/metastore_partition.proto
// Protobuf Java Version: 4.33.0

package com.google.cloud.bigquery.storage.v1alpha;

@com.google.protobuf.Generated
public interface UpdateMetastorePartitionRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.bigquery.storage.v1alpha.UpdateMetastorePartitionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. The metastore partition to be updated.
   * </pre>
   *
   * <code>
   * .google.cloud.bigquery.storage.v1alpha.MetastorePartition metastore_partition = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return Whether the metastorePartition field is set.
   */
  boolean hasMetastorePartition();

  /**
   *
   *
   * <pre>
   * Required. The metastore partition to be updated.
   * </pre>
   *
   * <code>
   * .google.cloud.bigquery.storage.v1alpha.MetastorePartition metastore_partition = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   *
   * @return The metastorePartition.
   */
  com.google.cloud.bigquery.storage.v1alpha.MetastorePartition getMetastorePartition();

  /**
   *
   *
   * <pre>
   * Required. The metastore partition to be updated.
   * </pre>
   *
   * <code>
   * .google.cloud.bigquery.storage.v1alpha.MetastorePartition metastore_partition = 1 [(.google.api.field_behavior) = REQUIRED];
   * </code>
   */
  com.google.cloud.bigquery.storage.v1alpha.MetastorePartitionOrBuilder
      getMetastorePartitionOrBuilder();

  /**
   *
   *
   * <pre>
   * Optional. The list of fields to update.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   *
   * @return Whether the updateMask field is set.
   */
  boolean hasUpdateMask();

  /**
   *
   *
   * <pre>
   * Optional. The list of fields to update.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   *
   * @return The updateMask.
   */
  com.google.protobuf.FieldMask getUpdateMask();

  /**
   *
   *
   * <pre>
   * Optional. The list of fields to update.
   * </pre>
   *
   * <code>.google.protobuf.FieldMask update_mask = 2 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   */
  com.google.protobuf.FieldMaskOrBuilder getUpdateMaskOrBuilder();
}
