on:
  pull_request:
    paths-ignore:
      - 'tutorials/**'
      // this is a dummy change for demonstration
name: samples
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run checkstyle
        run: mvn -P lint --quiet --batch-mode checkstyle:check
        working-directory: samples/snippets
