on:
  pull_request:
    paths-ignore:
      - 'tutorials/**'
name: samples
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Run checkstyle
        run: mvn -P lint --quiet --batch-mode checkstyle:check
        working-directory: samples/snippets
